### 1.2.1 Пример

**Задача:**

Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация 
начинается с нуля.

In [56]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


### 1.2.2 Пример

**Задача:**

Пример. Выполнить следующее: 
1. Создать вектор (одномерный массив) размера 10, заполненный 
нулями. 
2. Создать вектор размера 10, заполненный единицами. 
3. Создать вектор размера 10, заполненный заданным числом. 
4. Создать вектор со значениями от 10 до 19.

In [57]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, '\n', b, '\n', c, '\n', d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


### 1.2.3 Пример

**Задача:**

Создать массив 10x10 со случайными значениями, найти минимум, 
максимум и среднее значение.

In [58]:
z = np.random.random((10, 10))
z_min, z_max, z_mean = z.min(), z.max(), z.mean()
print(z_min, z_max, z_mean)

0.014071124235336407 0.9726920412959109 0.4538165457884413


### 1.2.4 Пример

**Задача:**

Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [59]:
a = np.arange(25).reshape(5, 5)
a[[0, 1]] = a[[1, 0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 1.2.5 Пример

**Задача:**

Выяснить результат следующих выражений:
`0 * np.nan`
`np.nan == np.nan`
`np.inf > np.nan`
`np.nan - np.nan`
`0.3 == 3 * 0.1`

In [60]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### 1.2.6 Пример

**Задача:**

Отсортировать массив.

In [61]:
array = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(array))

[1 2 3 4 5 6 7 8]


### 1.3.1

**Задача:**

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и 
единицами.

In [62]:
chessboard = np.indices((8, 8))
chessboard = (chessboard[0] + chessboard[1]) % 2
print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 1.3.2

**Задача:**

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания 
необходимо использовать функцию arrange.

In [63]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 1.3.3

**Задача:**

Создать массив 3x3x3 со случайными значениями.

In [64]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.51759845 0.93515855 0.24659566]
  [0.07451195 0.61544093 0.82772365]
  [0.10084818 0.8478007  0.42660018]]

 [[0.20739889 0.73794386 0.05017711]
  [0.64232109 0.59534826 0.45702036]
  [0.87135885 0.12427896 0.95649889]]

 [[0.70366169 0.04762737 0.45493009]
  [0.52003032 0.15283465 0.9360573 ]
  [0.33978632 0.68725897 0.0108571 ]]]


### 1.3.4

**Задача:**

Создать матрицу с 0 внутри, и 1 на границах.

In [65]:
inner = np.zeros((3, 3), dtype=int)
matrix = np.pad(inner, pad_width=1, mode='constant', constant_values=1)
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### 1.3.5

**Задача:**

Создайте массив и отсортируйте его по убыванию.

In [66]:
array = np.random.randint(1, 100, 10)
sorted_array = np.sort(array)[::-1]
print(sorted_array)

[93 74 69 68 41 38 37 13  8  3]


### 1.3.6

**Задача:**

Создайте матрицу, выведите ее форму, размер и размерность.

In [67]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])
print(f'Форма матрицы: {matrix.shape}')
print(f'Размер матрицы: {matrix.size}')
print(f'Размерность матрицы: {matrix.ndim}')

Форма матрицы: (3, 4)
Размер матрицы: 12
Размерность матрицы: 2


### 2.2.1 Пример

**Задача:**

Создать Series из списка Python, словаря Python, и массива Numpy 
(установить буквенные метки для последнего).

In [68]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a': 1, 'b': 2, 'c': 3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


### 2.2.2 Пример

**Задача:**

Дано два Series. Напечатать их первые элементы и все элементы после 
третьего (во втором фрейме).

In [69]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


### 2.2.3 Пример

**Задача:**

Создайте новый фрейм данных.

In [70]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

### 2.2.4 Пример

**Задача:**

Загрузите фрейм данных по ссылке: 
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titan
ic.csv

In [71]:
dataframe = pd.read_csv('./datasets/airlines.csv')
dataframe.head(5)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0

### 2.2.5 Пример

**Задача:**

Пронализировать характеристики фрейма данных.

In [72]:
display(dataframe.head(2))
display(dataframe.tail(3))
print('Shape:', dataframe.shape)
display(dataframe.describe())

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

Shape: (539383, 8)


Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000   
mean     2427.928630       3.929668     802.728963     132.202007   
std      2067.429837       1.914664     278.045911      70.117016   
min         1.000000       1.000000      10.000000       0.000000   
25%       712.000000       2.000000     565.000000      81.000000   
50%      1809.000000       4.000000     795.000000     115.000000   
75%      3745.000000       5.000000    1035.000000     162.000000   
max      7814.000000       7.000000    1439.000000     655.000000   

               Delay  
count  539383.000000  
mean        0.445442  
std         0.497015  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

### 2.2.6 Пример

**Задача:**

Выберите индивидуальные данные или срезы фрейма данных.

In [73]:
dataframe.iloc[1:4]

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1

### 2.2.7 Пример

**Задача:**

Требуется отобрать строки фрейма данных на основе некоторого 
условия. Необходимо сформировать новый фрейм данных из пассажиров 
первого класса.

In [74]:
dataframe[dataframe['DayOfWeek'] == 3].head(2)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1

### 2.3.1

**Задача:**

Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [75]:
a = pd.Series([2, 3, 5])
b = pd.Series([1, 1, 1])
sum_sq = ((a - b) ** 2).sum()
np.sqrt(sum_sq)

np.float64(4.58257569495584)

### 2.3.2

**Задача:**

Найдите в Интернете ссылку на любой csv файл и сформируйте из него 
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [76]:
airlines_dataframe = pd.read_csv('./datasets/airlines.csv')
airlines_dataframe.head()

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0

### 2.3.3

**Задача:**

Проделайте с получившемся из предыдущего задания фреймом данных 
те же действия, что и в примерах 2.2.5 -2.2.7.

In [77]:
display(airlines_dataframe.head(2))
display(airlines_dataframe.tail(2))
print('Shape:', airlines_dataframe.shape)
display(airlines_dataframe.describe())

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

Shape: (539383, 8)


Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000   
mean     2427.928630       3.929668     802.728963     132.202007   
std      2067.429837       1.914664     278.045911      70.117016   
min         1.000000       1.000000      10.000000       0.000000   
25%       712.000000       2.000000     565.000000      81.000000   
50%      1809.000000       4.000000     795.000000     115.000000   
75%      3745.000000       5.000000    1035.000000     162.000000   
max      7814.000000       7.000000    1439.000000     655.000000   

               Delay  
count  539383.000000  
mean        0.445442  
std         0.497015  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

### 3.2.1 Пример

**Задача:**

Прошкалируйте числовой признак в диапазон между двумя значениями.

In [78]:
from sklearn import preprocessing
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

### 3.2.2 Пример

**Задача:**

Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [79]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)

print('Среднее:', round(standardized.mean()))
print('Стандартное отклонение:', standardized.std())
standardized

Среднее: 0
Стандартное отклонение: 1.0


array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

### 3.2.3

**Задача:**

Дан фрейм данных
```python
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21], 
 'B':[103.02,107.26,110.35,114.23,114.68], 
 'C':['big','small','big','small','small']})
````


Необходимо масштабировать его числовые столбцы.

In [80]:
scaler = preprocessing.MinMaxScaler()
dfTest = pd.DataFrame({
    'A': [14.00, 90.20, 90.95, 96.27, 91.21],
    'B': [103.02, 107.26, 110.35, 114.23, 114.68],
    'C': ['big', 'small', 'big', 'small', 'small'],
})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

### 3.3.2

**Задача:**

Загрузить фрейм данных по ссылке : 
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. 
Необходимо выполнить нормализацию первого числового признака 
(sepal_length_cm) с использованием минимаксного преобразования, а 
второго (sepal_width_cm) с задействованием z -масштабирования.

In [81]:
minmax_scaler = preprocessing.MinMaxScaler()
standard_scaler = preprocessing.StandardScaler()

dataframe = pd.read_csv('./datasets/iris.csv')

dataframe[['sepal_length_cm']] = minmax_scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = standard_scaler.fit_transform(dataframe[['sepal_width_cm']])
dataframe.head(5)


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa